### ISSUE TITLE
Your email password is public

### ISSUE THREAD

**Issue by r04r** [Ahimta/photo-app-backend-node#1]
https://github.com/Ahimta/photo-app-backend-node/blob/7b57817788507244ff4023d577eea956fd9ff173/app/mailer.coffee#L9

Don't just change your code. Earlier revisions may still be found. Change your password ASAP!

**Comment by Ahimta** [comment]
@r04r thanks for your concern.
This is a Mandrillapp API key not my email password.
Fortunately, there's no real risk in hard-coding it here.

One reason that it's safe in this case is that I am not using a DNS domain signing for sending emails.
So even though it's safe to hard-code it in my case, it can be not safe in other cases.
